### ISSUE TITLE
QuarkusUpstream: Quarkus application with Helm extension is throwing a build failure exception 

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#114]
Quarkus-helm version: 0.1.1
Quarkus version: `Upstream`
Dekorate: `3.0.2`
error: `java.lang.NoClassDefFoundError: io/dekorate/helm/util/HelmExpressionParser`

Related to: https://github.com/quarkusio/quarkus/pull/28438/files

Stacktrace
```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (build) on project helm-minimum: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkiverse.helm.deployment.HelmProcessor#generateResources threw an exception: java.lang.NoClassDefFoundError: io/dekorate/helm/util/HelmExpressionParser
Error:  	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.replaceValuesInYamls(QuarkusHelmWriterSessionListener.java:442)
Error:  	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.processTemplates(QuarkusHelmWriterSessionListener.java:352)
Error:  	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.writeHelmFiles(QuarkusHelmWriterSessionListener.java:113)
Error:  	at io.quarkiverse.helm.deployment.HelmProcessor.generateResources(HelmProcessor.java:120)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Error:  	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  Caused by: java.lang.ClassNotFoundException: io.dekorate.helm.util.HelmExpressionParser
Error:  	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
Error:  	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
Error:  	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
Error:  	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
Error:  	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:500)
Error:  	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:450)
Error:  	... 15 more
Error:  -> [Help 1]
```

**Comment by Sgitario** [comment]
Indeed, Quarkus Helm is not compatible with the unreleased upstream version of Quarkus. 
For more information, see the compatibility with Quarkus table. Closing as there is nothing we can do here.
