### ISSUE TITLE
Problem with changed signature of YamlExpressionParser.readAndReplace

### ISSUE THREAD

**Issue by wgresshoff** [quarkiverse/quarkus-helm#193]
I can't generate the helm manifests any more:
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.Alpha6:build (default) on project memoryalpha-to-inveniordm: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.helm.deployment.HelmProcessor#generateResources threw an exception: java.lang.NoSuchMethodError: 'java.util.Set io.github.yamlpath.YamlExpressionParser.readAndReplace(java.lang.String, java.lang.String)'
[ERROR] 	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.readAndSet(QuarkusHelmWriterSessionListener.java:635)
[ERROR] 	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.replaceValuesInYamls(QuarkusHelmWriterSessionListener.java:541)
[ERROR] 	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.processTemplates(QuarkusHelmWriterSessionListener.java:398)
[ERROR] 	at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.writeHelmFiles(QuarkusHelmWriterSessionListener.java:115)
[ERROR] 	at io.quarkiverse.helm.deployment.HelmProcessor.doGenerateResources(HelmProcessor.java:187)
[ERROR] 	at io.quarkiverse.helm.deployment.HelmProcessor.generateResources(HelmProcessor.java:148)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

This is a problem starting with yaml-path > 0.0.4 (beginning with 0.0.5 the second parameter was changed to Object). When I add yaml-path 0.0.4 to my pom.xml helm manifest generation works again.

**Comment by wgresshoff** [comment]
Great news, thanks!
