### ISSUE TITLE
Unexpecetd error when we are running helm extension on Quarkus Upstream

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#29]
I am using `Quarkiverse/Quarkus-helm` extension against Quarkus `999-SNAPSHOT` and when the extension is generating the `values.yaml` from my `application.properties` I am getting the following error:

```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project examples-quarkus-helm: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: r]: Build step io.quarkiverse.helm.deployment.HelmProcessor#feature threw an exception: java.lang.NoSuchMethodError: 'java.lang.String[] io.dekorate.ConfigReference.getJsonPaths()'
Error:  	at io.quarkiverse.helm.deployment.HelmWriterSessionListener.replaceValuesInYamls(HelmWriterSessionListener.java:251)
Error:  	at io.quarkiverse.helm.deployment.HelmWriterSessionListener.processSourceFiles(HelmWriterSessionListener.java:210)
Error:  	at io.quarkiverse.helm.deployment.HelmWriterSessionListener.writeHelmFiles(HelmWriterSessionListener.java:84)
Error:  	at io.quarkiverse.helm.deployment.HelmProcessor.feature(HelmProcessor.java:37)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Error:  	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  -> [Help 1]
```

**Note:** On `Quarkus 2.9.2.Final` or `Quarkus 2.10.2.Final` works as expected

application.properties:

```
# Application properties
quarkus.openshift.expose=true
quarkus.openshift.route.expose=true

quarkus.kubernetes.expose=true
quarkus.kubernetes.ingress.expose=true

quarkus.container-image.image=quay.io/quarkusqeteam/examples-quarkus-helm:1.2.1.Beta1-SNAPSHOT
quarkus.kubernetes.host=examples-quarkus-helm.apps.ocp4-10.dynamic.quarkus
quarkus.container-image.builder=docker

```

**Comment by Sgitario** [comment]
This is actually expected. Quarkus Quarkiverse extensions should only be compatible with released versions of Quarkus, not 999-SNAPSHOT.
