### ISSUE TITLE
If `quarkus-maven-plugin` is overwritten on a child pom then helm chart generation fails

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkus-helm#81]
QuarkusVersion: `Upstream`
Quarkus-Helm: `0.0.5`

If I have a parent pom with a general `quarkus-maven-plugin` definition and I overwrite this configuration in a child pom, then I am getting the following error and the application is not deployed

Error stacktrace
```
[ERROR] Caused by: java.nio.file.FileAlreadyExistsException: /home/pablojosegonzalezgranados/Documents/workspace/quarkus-test-suite/helm/helm-simple-app/target/helm/kubernetes/my-chart/templates/NOTES.txt
[ERROR]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
[ERROR]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[ERROR]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[ERROR]         at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[ERROR]         at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[ERROR]         at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
[ERROR]         at java.base/java.nio.file.Files.copy(Files.java:3067)
[ERROR]         at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.addNotesIntoTemplatesFolder(QuarkusHelmWriterSessionListener.java:129)
[ERROR]         at io.quarkiverse.helm.deployment.QuarkusHelmWriterSessionListener.writeHelmFiles(QuarkusHelmWriterSessionListener.java:103)
[ERROR]         ... 12 more
[ERROR] -> [Help 1]
```

Parent pom `quarkus-maven-plugin` definition
```
 <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <executions>
                    <execution>
                        <id>build</id>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Child pom

```
<plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <systemProperties>
                        <quarkus.container-image.build>true</quarkus.container-image.build>
                        <quarkus.container-image.push>true</quarkus.container-image.push>
                    </systemProperties>
                </configuration>
            </plugin>
```

**Comment by Sgitario** [comment]
I can't reproduce this issue using Quarkus Helm main. I think this issue was solved by https://github.com/quarkiverse/quarkus-helm/pull/78. 

Can you confirm that this is working for you using the `main` branch?

**Comment by pjgg** [comment]
Fixed on Upstream!.
